name: Rust

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --features full --verbose
